/// Unicode glyph tables backing [LatexToUnicode] (see that file's
/// header for the architecture and sources).
abstract final class LatexData {
  /// Macro name to Unicode symbol (Greek, operators, relations...).
  static const Map<String, String> sym = {
    'alpha': 'α',
    'beta': 'β',
    'gamma': 'γ',
    'delta': 'δ',
    'epsilon': 'ε',
    'zeta': 'ζ',
    'eta': 'η',
    'theta': 'θ',
    'iota': 'ι',
    'kappa': 'κ',
    'lambda': 'λ',
    'mu': 'μ',
    'nu': 'ν',
    'xi': 'ξ',
    'pi': 'π',
    'rho': 'ρ',
    'sigma': 'σ',
    'tau': 'τ',
    'upsilon': 'υ',
    'phi': 'ϕ',
    'varphi': 'φ',
    'chi': 'χ',
    'psi': 'ψ',
    'omega': 'ω',
    'Gamma': 'Γ',
    'Delta': 'Δ',
    'Theta': 'Θ',
    'Lambda': 'Λ',
    'Xi': 'Ξ',
    'Pi': 'Π',
    'Sigma': 'Σ',
    'Phi': 'Φ',
    'Psi': 'Ψ',
    'Omega': 'Ω',
    'cdot': '⋅',
    'times': '×',
    'div': '÷',
    'pm': '±',
    'mp': '∓',
    'ast': '∗',
    'star': '⋆',
    'bullet': '•',
    'circ': '∘',
    'degree': '°',
    'prime': '′',
    'sum': '∑',
    'prod': '∏',
    'int': '∫',
    'iint': '∬',
    'iiint': '∭',
    'oint': '∮',
    'partial': '∂',
    'nabla': '∇',
    'infty': '∞',
    'approx': '≈',
    'equiv': '≡',
    'neq': '≠',
    'ne': '≠',
    'eq': '=',
    'le': '≤',
    'leq': '≤',
    'leeq': '≤',
    'ge': '≥',
    'geq': '≥',
    'll': '≪',
    'gg': '≫',
    'rightarrow': '→',
    'leftarrow': '←',
    'Rightarrow': '⇒',
    'Leftarrow': '⇐',
    'implies': '⇒',
    'iff': '⇔',
    'to': '→',
    'mapsto': '↦',
    'longrightarrow': '⟶',
    'longleftarrow': '⟵',
    'leftrightarrow': '↔',
    'Leftrightarrow': '⇔',
    'Longleftrightarrow': '⟺',
    // \Alpha is non-standard LaTeX (MathJax extension only); approximate as
    // plain capital A since the glyph family matches.
    'Alpha': 'A',
    'wedge': '∧',
    'vee': '∨',
    'land': '∧',
    'lor': '∨',
    'neg': '¬',
    'lnot': '¬',
    'cap': '∩',
    'cup': '∪',
    'subset': '⊂',
    'subseteq': '⊆',
    'supset': '⊃',
    'supseteq': '⊇',
    'setminus': '∖',
    'oplus': '⊕',
    'otimes': '⊗',
    'emptyset': '∅',
    'varnothing': '∅',
    'in': '∈',
    'ni': '∋',
    'notin': '∉',
    'forall': '∀',
    'exists': '∃',
    'mid': '∣',
    'nmid': '∤',
    'perp': '⊥',
    'parallel': '∥',
    'ldots': '…',
    'cdots': '⋯',
    'dots': '…',
    'vdots': '⋮',
    'ddots': '⋱',
    'sim': '∼',
    'simeq': '≃',
    'cong': '≅',
    'propto': '∝',
    'ell': 'ℓ',
    'varepsilon': 'ε',
    'angle': '∠',
    'therefore': '∴',
    'because': '∵',
    'triangle': '△',
    'square': '□',
    'langle': '⟨',
    'rangle': '⟩',
    'lfloor': '⌊',
    'rfloor': '⌋',
    'lceil': '⌈',
    'rceil': '⌉',
    '|': '∥',
    'sin': 'sin',
    'cos': 'cos',
    'tan': 'tan',
    'cot': 'cot',
    'sec': 'sec',
    'csc': 'csc',
    'log': 'log',
    'ln': 'ln',
    'exp': 'exp',
    'max': 'max',
    'min': 'min',
    'lim': 'lim',
    'lg': 'lg',
    'arctan': 'arctan',
    'arcsin': 'arcsin',
    'arccos': 'arccos',
    'gcd': 'gcd',
    'lcm': 'lcm',
    'mod': 'mod',
    'ker': 'ker',
    'deg': 'deg',
    'dim': 'dim',
    'bigcup': '⋃',
    'bigcap': '⋂',
    'bigoplus': '⨁',
    'odot': '⊙',
  };

  /// ASCII char to superscript glyph; missing glyphs degrade to `^(..)`.
  static const Map<String, String> supMap = {
    '0': '⁰',
    '1': '¹',
    '2': '²',
    '3': '³',
    '4': '⁴',
    '5': '⁵',
    '6': '⁶',
    '7': '⁷',
    '8': '⁸',
    '9': '⁹',
    '+': '⁺',
    '-': '⁻',
    '=': '⁼',
    'a': 'ᵃ',
    'b': 'ᵇ',
    'c': 'ᶜ',
    'd': 'ᵈ',
    'e': 'ᵉ',
    'f': 'ᶠ',
    'g': 'ᵍ',
    'h': 'ʰ',
    'i': 'ⁱ',
    'j': 'ʲ',
    'k': 'ᵏ',
    'l': 'ˡ',
    'm': 'ᵐ',
    'n': 'ⁿ',
    'o': 'ᵒ',
    'p': 'ᵖ',
    'r': 'ʳ',
    's': 'ˢ',
    't': 'ᵗ',
    'u': 'ᵘ',
    'v': 'ᵛ',
    'w': 'ʷ',
    'x': 'ˣ',
    'y': 'ʸ',
    'z': 'ᶻ',
    'T': 'ᵀ',
  };

  /// ASCII char to subscript glyph; missing glyphs degrade to `_(..)`.
  static const Map<String, String> subMap = {
    '0': '₀',
    '1': '₁',
    '2': '₂',
    '3': '₃',
    '4': '₄',
    '5': '₅',
    '6': '₆',
    '7': '₇',
    '8': '₈',
    '9': '₉',
    '+': '₊',
    '-': '₋',
    '=': '₌',
    'i': 'ᵢ',
    'j': 'ⱼ',
    'n': 'ₙ',
    'k': 'ₖ',
    'a': 'ₐ',
    'e': 'ₑ',
    't': 'ₜ',
    'x': 'ₓ',
    'h': 'ₕ',
    'm': 'ₘ',
    'l': 'ₗ',
    'r': 'ᵣ',
    's': 'ₛ',
    'u': 'ᵤ',
    'v': 'ᵥ',
  };

  /// Decorative macros producing empty or whitespace text.
  static const Map<String, String> voidCmds = {
    'left': '',
    'right': '',
    'big': '',
    'Big': '',
    'bigl': '',
    'bigr': '',
    'Bigl': '',
    'Bigr': '',
    'bigg': '',
    'Bigg': '',
    'biggl': '',
    'biggr': '',
    'limits': '',
    'quad': ' ',
    'qquad': ' ',
    // Space commands (single-char commands like \, \; \! \:)
    ',': ' ',
    ';': ' ',
    ':': ' ',
    '!': '',
    'nonumber': '',
    'notag': '',
    'displaystyle': '',
    'textstyle': '',
  };

  /// Style name to (upper, lower) offsets in U+1D400.
  static const Map<String, (int, int)> styleOffsets = {
    'bold': (0x1D400, 0x1D41A),
    'italic': (0x1D434, 0x1D44E),
    'bold-italic': (0x1D468, 0x1D482),
    'script': (0x1D49C, 0x1D4B6),
    'bold-script': (0x1D4D0, 0x1D4EA),
    'fraktur': (0x1D504, 0x1D51E),
    'doublestruck': (0x1D538, 0x1D552),
    'bold-fraktur': (0x1D56C, 0x1D586),
    'sans': (0x1D5A0, 0x1D5BA),
    'sans-bold': (0x1D5D4, 0x1D5EE),
    'sans-italic': (0x1D608, 0x1D622),
    'sans-bold-italic': (0x1D63C, 0x1D656),
    'monospace': (0x1D670, 0x1D68A),
  };

  /// U+1D400 holes: chars already occupied by an earlier style.
  static const Map<String, Map<String, int>> styleExceptions = {
    'italic': {'h': 0x210e},
    'script': {
      'B': 0x212c,
      'E': 0x2130,
      'F': 0x2131,
      'H': 0x210b,
      'I': 0x2110,
      'L': 0x2112,
      'M': 0x2133,
      'R': 0x211b,
      'e': 0x212f,
      'g': 0x210a,
      'o': 0x2134,
    },
    'fraktur': {
      'C': 0x212d,
      'H': 0x210c,
      'I': 0x2111,
      'R': 0x211c,
      'Z': 0x2128,
    },
    'doublestruck': {
      'C': 0x2102,
      'H': 0x210d,
      'N': 0x2115,
      'P': 0x2119,
      'Q': 0x211a,
      'R': 0x211d,
      'Z': 0x2124,
    },
  };

  /// Digit styles (only 5 of 13 have math digit glyphs).
  static const Map<String, int> digitOffsets = {
    'bold': 0x1D7CE,
    'doublestruck': 0x1D7D8,
    'sans': 0x1D7E2,
    'sans-bold': 0x1D7EC,
    'monospace': 0x1D7F6,
  };

  /// Style-swap macros to styleOffsets names.
  static const Map<String, String> styleCmds = {
    'mathbb': 'doublestruck',
    'Bbb': 'doublestruck',
    'mathcal': 'script',
    'mathscr': 'script',
    'mathfrak': 'fraktur',
    'mathbf': 'bold',
    'boldsymbol': 'bold',
    'mathit': 'italic',
    'mathbfit': 'bold-italic',
    'mathsf': 'sans',
    'mathtt': 'monospace',
  };

  /// Accent macros to combining characters.
  static const Map<String, String> accents = {
    'vec': '\u20d7',
    'overrightarrow': '\u20d7',
    'hat': '\u0302',
    'tilde': '\u0303',
    'bar': '\u0304',
    'overline': '\u0305',
    'underline': '\u0332',
    'dot': '\u0307',
  };

  /// Plain-text macros that drop styling.
  static const Set<String> plainCmds = {
    'text',
    'mathrm',
    'rm',
    'operatorname',
    'emph',
    'mathnormal',
  };

  /// Macros accepting an optional `[...]` argument.
  static const Set<String> optCmds = {'sqrt'};

  /// Environment names rendered as matrices.
  static const Set<String> matrixEnvs = {
    'pmatrix',
    'matrix',
    'bmatrix',
    'vmatrix',
    'Vmatrix',
    'smallmatrix',
  };

  /// Literal chars produced by backslash escapes (`{`, `%` ...).
  static const String literalChars = '{}&%#_\$[]~ ';

  /// FIGURE SPACE: half-width monospace that survives bilibili's whitespace
  /// flattening; pads matrix cells inside the box frame.
  static const String padChar = '\u2007';
}
